/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hackerrank

fun main(args: Array<String>) {
    SpiesRevised().execute(7).let {
        println(it.size)
        println(it.joinToString(separator = " "))
    }
}

class SpiesRevised {
    fun execute(size: Int): List<Int> {
        val result = mutableListOf<Int>()
        for (i in 1..(size / 2 + 1) * 2 step 2) result.add(i)
        for (i in 2..size step 2) result.add(i)
        return result
    }
}