/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package hackerrank

import kotlin.test.Test
import kotlin.test.assertTrue

class SpiesRevisedTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = SpiesRevised()
        assertTrue(classUnderTest.execute(), "someLibraryMethod should return 'true'")
    }
}
