/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package main

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test


class DummyTest {
    @Test
    fun someLibraryMethodReturnsTrue() {
        assertThat(true).isTrue
    }
}
